# Generated by Django 3.2.13 on 2023-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEnergyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='系列名称')),
                ('serie_img', models.CharField(blank=True, max_length=200, null=True, verbose_name='系列URL')),
                ('serie_pinyin', models.CharField(blank=True, max_length=200, null=True, verbose_name='系列名称拼音')),
                ('serie_level', models.FloatField(blank=True, default=0, verbose_name='系列等级')),
                ('min_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='最低价格')),
                ('max_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='最高价格')),
                ('min_guide_price', models.FloatField(blank=True, default=0, verbose_name='最低指导价格')),
                ('max_guide_price', models.FloatField(blank=True, default=0, verbose_name='最高指导价格')),
                ('new_type', models.FloatField(blank=True, default=0, verbose_name='新类型')),
                ('max_energy_range', models.FloatField(blank=True, default=0, verbose_name='最大里程')),
                ('max_pure_energy_range', models.FloatField(blank=True, default=0, verbose_name='纯电续航里程')),
                ('model_config_video_num', models.FloatField(blank=True, default=0, verbose_name='车型款数')),
                ('has_subsidy', models.FloatField(blank=True, default=0, verbose_name='是否有补贴')),
                ('model_count', models.FloatField(blank=True, default=0, verbose_name='车型款数')),
            ],
            options={
                'verbose_name': '新能源电动车价格表',
                'verbose_name_plural': '新能源电动车价格表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户密码')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户账号表',
                'verbose_name_plural': '用户账号表',
                'managed': True,
            },
        ),
    ]
